# 中文轉阿拉伯

In [ ]:
dict ={u'零':0, u'一':1, u'二':2, u'三':3, u'四':4, u'五':5, u'六':6, u'七':7, u'八':8, u'九':9, u'十':10, u'百':100, u'千':1000, u'万':10000,
       u'０':0, u'１':1, u'２':2, u'３':3, u'４':4, u'５':5, u'６':6, u'７':7, u'８':8, u'９':9,
       u'0':0, u'1':1, u'2':2, u'3':3, u'4':4, u'5':5, u'6':6, u'7':7, u'8':8, u'9':9,
       u'壹':1, u'贰':2, u'叁':3, u'肆':4, u'伍':5, u'陆':6, u'柒':7, u'捌':8, u'玖':9, u'拾':10, u'什':10, u'佰':100, u'仟':1000, u'萬':10000,
       u'兩':2,u'貳':2, u'參':3, u'肆':4, u'伍':5, u'陸':6, u'佰':100, u'仟':1000, u'萬':10000,
       u'亿':100000000,u'億':100000000,u'兆':1000000000000}
def getResultForDigit(a, encoding="utf-8"):
    if not isinstance(a, str):
        a = a.decode(encoding)
    count = 0
    result = 0
    tmp = 0
    Billion = 0
    while count < len(a):
        tmpChr = a[count]
        #print tmpChr
        tmpNum = dict.get(tmpChr, None)
        #如果等于1亿
        if tmpNum is None:
            pass
        elif tmpNum == 100000000:
            result = result + tmp
            result = result * tmpNum
            #获得亿以上的数量，将其保存在中间变量Billion中并清空result
            Billion = Billion * 100000000 + result
            result = 0
            tmp = 0
        #如果等于1万
        elif tmpNum == 10000:
            result = result + tmp
            result = result * tmpNum
            tmp = 0
        #如果等于十或者百，千
        elif tmpNum >= 10:
            if tmp == 0:
                tmp = 1
            result = result + tmpNum * tmp
            tmp = 0
        #如果是个位数
        elif tmpNum is not None:
            tmp = tmp * 10 + tmpNum
        count += 1
    result = result + tmp
    result = result + Billion
    return result

In [9]:
# 將這個公式的.py檔案放進D:\anaconda\Lib內即可直接import使用
# 如果要變成套件，則放進D:\anaconda\Lib的 套件名稱(my_api) 資料夾內，並加入init.py檔

In [2]:
from my_api import TextMining
TextMining.

# dict取得value 沒key時的寫法

In [ ]:
#用[a]如果沒有key a會產生error 但用dict.get(a,b) 如果key a 不存在 則會回傳b值
adict["j3"]
adict.get("j3","sss")

# 單行if

In [ ]:
#a if b else c(b成立則a 否則c)
(111 if 3>4 else 222)

# 解開list(list)的快速方法

In [2]:
lts = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[ele for lt in lts for ele in lt]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# python套件如何做?
http://www.codedata.com.tw/python/python-tutorial-the-2nd-class-3-function-module-class-package/

自己做import

#檔案有tryyyy.py 裡面有def函數跟某些數值 可直接import tryyyy
#資料夾名稱(bank)裡面有init.py檔則被視為套件、可import資料夾名稱.裡面的py檔 >>import bank.bank

In [ ]:
import tryyyy
print(tryyyy.max(10,30),tryyyy.pi)

In [ ]:
import bank.bank
acct = bank.account('Justin', '123-4567', 1000)
bank.deposit(acct, 500)
bank.withdraw(acct, 200)
print (bank.to_str(acct))

In [28]:
#用__init__(self,name,tele,save)方法寫
class bank:
    def __init__(self,name,tele,have):
        self.name=name
        self.tele=tele
        self.have=have
    
    def deposit(self,savein):
        if savein>0:
            self.have=self.have+savein
        else:
            raise ValueError("you should save positive money")
        
    def withdraw(self,draw):
        if draw>0:
            if self.have>draw:
                self.have=self.have-draw
            else:
                raise RuntimeError("your have is not enough")
        else:
            raise ValueError("you should draw positive money")
    def __str__(self):
        return "bank({},{},{})".format(self.name,self.tele,self.have)

In [30]:
acc=bank("Andy","0953564878",400000)
acc.deposit(5000)
print(acc)

acc.withdraw(50500)
print(acc)

bank(Andy,0953564878,405000)
bank(Andy,0953564878,354500)


# lambda用法   lambda  a, b, c: you want to do from a,b,c
>sum=lambda o, elem: o + elem

>p=lambda o, elem: o *elem

# reduce用法 (公式 ,需相同計算方式的list,計算初始)
>reduce(sum,[1,2,3,4,5,6],5)
5+1+2+3+4+5+6

>reduce(p,[3,3,3,3],1)
1\*3\*3\*3\*3


In [34]:
from functools import reduce

summ=lambda a, b: a + b
reduce(sum,[1,2,3,4,5,6],5)
#5+1+2+3+4+5+6

26

In [33]:
p=lambda o, elem: o *elem
reduce(p,[3,3,3,3],1)
#>1*3*3*3*3

81

# GUI

In [37]:
import tkinter as tk
 
win=tk.Tk()
win.title("My First Tk GUI")#給標題
label=tk.Label(win, text="Hello World!")
label.pack() #顯上label
button=tk.Button(win, text="OK")
button.pack()#顯示botton
win.resizable(0,0)#禁止調整大小
win.mainloop()

In [38]:
from tkinter import *
win=Tk()
win.title("Tk GUI")
label=Label(win, text="Hello World!")
button=Button(win, text="OK")
label.pack()
button.pack()
win.mainloop()

In [39]:
from tkinter import *
win=Tk()
win.title("Tk GUI")
label=Label(win, text="Hello World!")
button=Button(win, text="OK")
label.grid(column=0,row=0)
button.grid(column=0,row=2)
win.mainloop() 

In [40]:
from tkinter import *
win=Tk()
win.title("Tk GUI")
label=Label(win, text="Hello World!")
count=0
def clickOK():
    global count
    count=count + 1
    label.configure(text="Click OK " + str(count) + " times")
button=Button(win, text="OK", command=clickOK)
label.pack()
button.pack()
win.mainloop()

# 試寫TFIDF API

In [5]:
class TextMining:
    from collections import Counter
    import math
    '''You should [I] cutArticlelist for get TFIDF'''
    def __init__(self,cutArticlelist):
        self.cutArticlelist=cutArticlelist
    
    def getWordCountList(self,N=300):
        '''get all words(most appear limit 300)'''
        wordCountList=[Counter(pincut.split(" ")).most_common(N) for pincut in self.cutArticlelist]
        return wordCountList
    
#     def getWordSet(self,N=300):
#         wordCountlist=self.getWordCountList(N)
#         wordset=set()
#         for wordCount in wordCountlist:
#             wordset.update(dict(wordCount).keys())
#         print("共{}個字".format(len(wordset)))
#         return wordset

    def getTF(self,N=300):
        TFList=[]
        n=0
        for wordCount in self.getWordCountList(N):
            n+=1
            if n%1000==0:
                print(n)
            TF={}
            allwords=sum(dict(wordCount).values())
            for wordkv in wordCount:
                TF[wordkv[0]]=(wordkv[1]/allwords)
            TFList.append(TF)
        return TFList
    
    def getWordAppear(self,N=300):
        k=0
        wordappear={}
        for wordCount in self.getWordCountList(N):
            k+=1
            if k%3000==0:
                print(k)
            for word in dict(wordCount).keys():
                if word in wordappear:
                    wordappear[word]+=1
                else:
                    wordappear[word]=1
        return wordappear
    
    def getIDF(self,N=300):
        wordappear=self.getWordAppear(N)
        artN=len(self.cutArticlelist)
        IDFDict={word:math.log(artN/wordappear[word],10) for word in wordappear}
        return IDFDict
    
    def getTFIDF(self,N=300):
        TFList=self.getTF(N)
        IDFdict=self.getIDF(N)
        TFIDFList=[]
        for artTFdict in TFList:
            artTFIDF=Counter()
            for artword in artTFdict:
                artTFIDF[artword]=artTFdict[artword]*IDFdict[artword]
            TFIDFList.append(artTFIDF)
        return TFIDFList
    
    def __str__(self):
        return "TextMining({})".format(self.cutArticlelist)

In [9]:
import numpy as np
a=np.array([1,2,3])
a

# a=np.array([1,2,3])

array([1, 2, 3])

In [17]:
b=np.array([[1.5,2,3],[4,5,6]])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [18]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]])
c

array([[[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 3. ,  2. ,  1. ],
        [ 4. ,  5. ,  6. ]]])

In [19]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [20]:
np.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [25]:
d=np.arange(10,30,5)
d

array([10, 15, 20, 25])

In [26]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [30]:
e=np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [35]:
f=np.eye(5)
f

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [36]:
f=np.eye(3,4)
f

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [42]:
np.random.random(5)

array([ 0.58335928,  0.52324669,  0.29156031,  0.56717818,  0.03400959])

In [45]:
np.random.random((3,3))

array([[ 0.2011736 ,  0.65971363,  0.83272981],
       [ 0.23794851,  0.29040024,  0.24004346],
       [ 0.28470366,  0.90341337,  0.50584384]])

In [60]:
np.empty((3,2))

array([[ 1.5,  2. ],
       [ 3. ,  4. ],
       [ 5. ,  6. ]])

In [62]:
np.save('my_array', a)
np.savez('array.npz', a,b)

In [63]:
np.load('my_array.npy')

array([1, 2, 3])